/**
 * Comprehensive test suite for Forge CLI
 *
 * Tests three levels:
 * 1. Branch coverage — every conditional in every template exercised
 * 2. Build verification — mvn compile / npm install + tsc
 * 3. Runtime verification — apps start + health endpoints respond
 * 4. Merge correctness — layer merges produce correct content
 * 5. AI trace sweep — DEC-056 compliance
 */
import { compose } from '../src/core/composer.js';
import { writeFileSync, mkdirSync, rmSync, existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { execSync, spawn } from 'child_process';
import { createRequire } from 'module';

const OUT = `C:/Projects/forge-cli/test-output-comp-${Date.now()}`;
const MVN = 'C:/tools/apache-maven-3.9.14/bin/mvn.cmd';

mkdirSync(OUT, { recursive: true });

const results = { pass: 0, fail: 0, skip: 0, details: [] };

function record(suite, test, status, detail = '') {
  const icon = status === 'PASS' ? 'PASS' : status === 'SKIP' ? 'SKIP' : 'FAIL';
  console.log(`  [${icon}] ${test}${detail ? ' — ' + detail : ''}`);
  results[status === 'PASS' ? 'pass' : status === 'SKIP' ? 'skip' : 'fail']++;
  results.details.push({ suite, test, status, detail });
}

// ──────────────────────────────────────────────
// HELPERS
// ──────────────────────────────────────────────
function writeToDisk(files, dir) {
  for (const file of files) {
    const full = join(dir, file.path);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, file.content, 'utf-8');
  }
}

function fileExists(dir, path) {
  return existsSync(join(dir, path));
}

function fileContent(dir, path) {
  return readFileSync(join(dir, path), 'utf-8');
}

function assertFile(dir, path, suite, test) {
  if (!fileExists(dir, path)) {
    record(suite, test, 'FAIL', `Missing: ${path}`);
    return false;
  }
  return true;
}

function assertNoFile(dir, path, suite, test) {
  if (fileExists(dir, path)) {
    record(suite, test, 'FAIL', `Should not exist: ${path}`);
    return false;
  }
  return true;
}

function assertContains(dir, path, str, suite, test) {
  if (!fileExists(dir, path)) {
    record(suite, test, 'FAIL', `Missing file: ${path}`);
    return false;
  }
  const content = fileContent(dir, path);
  if (!content.includes(str)) {
    record(suite, test, 'FAIL', `${path} missing "${str}"`);
    return false;
  }
  return true;
}

function assertNotContains(dir, path, str, suite, test) {
  if (!fileExists(dir, path)) return true; // file not existing = doesn't contain
  const content = fileContent(dir, path);
  if (content.includes(str)) {
    record(suite, test, 'FAIL', `${path} should NOT contain "${str}"`);
    return false;
  }
  return true;
}

const AI_PATTERNS = ['Co-authored-by', 'Claude', 'Anthropic', 'ChatGPT', 'generated by', 'auto-generated', 'Copilot'];
const AI_CHECK_FILES = ['package.json', 'pom.xml', 'README.md', 'tsconfig.json', '.gitignore'];

function assertNoAiTrace(dir, suite, testPrefix) {
  let clean = true;
  for (const f of AI_CHECK_FILES.filter(f => fileExists(dir, f))) {
    const content = fileContent(dir, f).toLowerCase();
    for (const pat of AI_PATTERNS) {
      if (content.includes(pat.toLowerCase())) {
        record(suite, `${testPrefix}: AI trace in ${f}`, 'FAIL', `Found "${pat}"`);
        clean = false;
      }
    }
  }
  if (clean) record(suite, `${testPrefix}: AI trace sweep`, 'PASS');
  return clean;
}

function generate(config) {
  const files = compose(config);
  const dir = join(OUT, config.variables.projectName);
  writeToDisk(files, dir);
  return { files, dir };
}

function buildJava(dir) {
  execSync(`"${MVN}" compile -q`, { cwd: dir, stdio: 'pipe', timeout: 300000 });
}

function buildNode(dir) {
  execSync('npm install', { cwd: dir, stdio: 'pipe', timeout: 120000 });
  execSync('npx tsc --noEmit', { cwd: dir, stdio: 'pipe', timeout: 60000 });
}

function mvnTest(dir) {
  execSync(`"${MVN}" test -q`, { cwd: dir, stdio: 'pipe', timeout: 300000 });
}

function startAndCheck(dir, command, port, healthPath, timeout = 15000) {
  return new Promise((resolve) => {
    const [cmd, ...args] = command.split(' ');
    const proc = spawn(cmd, args, {
      cwd: dir,
      stdio: 'pipe',
      shell: true,
      env: { ...process.env, PORT: String(port), NODE_ENV: 'development' },
    });

    let settled = false;
    const timer = setTimeout(() => {
      if (!settled) {
        settled = true;
        proc.kill();
        resolve({ ok: false, error: 'Timeout waiting for server' });
      }
    }, timeout);

    const checkHealth = async () => {
      for (let i = 0; i < 30; i++) {
        if (settled) return;
        try {
          const res = await fetch(`http://localhost:${port}${healthPath}`);
          if (res.ok) {
            settled = true;
            clearTimeout(timer);
            const body = await res.text();
            proc.kill();
            resolve({ ok: true, status: res.status, body });
            return;
          }
        } catch {
          // server not ready yet
        }
        await new Promise(r => setTimeout(r, 500));
      }
    };

    proc.on('error', (err) => {
      if (!settled) {
        settled = true;
        clearTimeout(timer);
        resolve({ ok: false, error: err.message });
      }
    });

    // Give server a moment to bind then start checking
    setTimeout(checkHealth, 1000);
  });
}

// ──────────────────────────────────────────────
// SUITE 1: BRANCH COVERAGE
// Every conditional path in every template
// ──────────────────────────────────────────────
console.log('\n╔══════════════════════════════════════════════╗');
console.log('║  SUITE 1: BRANCH COVERAGE                    ║');
console.log('╚══════════════════════════════════════════════╝');

// --- backend-springboot: 3 auth patterns × 2 messaging options = 6 combos ---
const backendCombos = [
  { authPattern: 'OAuth2 + Azure AD', messaging: 'Azure Service Bus', tag: 'oauth2-asb' },
  { authPattern: 'OAuth2 + Azure AD', messaging: 'None', tag: 'oauth2-nomsg' },
  { authPattern: 'JWT', messaging: 'Azure Service Bus', tag: 'jwt-asb' },
  { authPattern: 'JWT', messaging: 'None', tag: 'jwt-nomsg' },
  { authPattern: 'None', messaging: 'Azure Service Bus', tag: 'noauth-asb' },
  { authPattern: 'None', messaging: 'None', tag: 'noauth-nomsg' },
];

for (const combo of backendCombos) {
  const suite = `backend-springboot/${combo.tag}`;
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'backend-springboot',
      variables: {
        projectName: `be-${combo.tag}`,
        className: 'TestSvc',
        groupId: 'com.test',
        packageName: 'com.test.testsvc',
        packagePath: 'com/test/testsvc',
        artifactName: 'testsvc',
        authPattern: combo.authPattern,
        messaging: combo.messaging,
        runtime: 'java',
      },
      layers: [],
    });

    record(suite, 'generates', 'PASS', `${files.length} files`);

    // Auth checks
    const pom = fileContent(dir, 'pom.xml');
    const hasSecDep = pom.includes('spring-boot-starter-security');
    const hasOauth = pom.includes('oauth2-resource-server');
    const hasAzureAd = pom.includes('active-directory');
    const hasAsb = pom.includes('spring-messaging-azure-servicebus');
    const hasSecTest = pom.includes('security-test');
    const hasDepMgmt = pom.includes('spring-cloud-azure-dependencies');

    // Security is always included (non-negotiable per bible)
    assertContains(dir, 'pom.xml', 'spring-boot-starter-security', suite, 'Security dep always present');
    assertFile(dir, 'src/main/java/com/test/testsvc/config/SecurityConfig.java', suite, 'SecurityConfig always exists');

    if (combo.authPattern === 'OAuth2 + Azure AD') {
      if (hasSecDep && hasOauth && hasAzureAd && hasSecTest)
        record(suite, 'OAuth2 deps in pom.xml', 'PASS');
      else
        record(suite, 'OAuth2 deps in pom.xml', 'FAIL', `sec=${hasSecDep} oauth=${hasOauth} azureAd=${hasAzureAd}`);

      // Check application.yml has OAuth2 config
      const appYml = fileContent(dir, 'src/main/resources/application.yml');
      if (appYml.includes('resourceserver'))
        record(suite, 'OAuth2 config in application.yml', 'PASS');
      else
        record(suite, 'OAuth2 config in application.yml', 'FAIL');

      // SecurityConfig should have oauth2ResourceServer and APPROLE_ prefix
      assertContains(dir, 'src/main/java/com/test/testsvc/config/SecurityConfig.java', 'oauth2ResourceServer', suite, 'SecurityConfig has OAuth2');
    } else if (combo.authPattern === 'JWT') {
      // JWT also uses oauth2-resource-server starter (for JWT validation)
      if (hasSecDep && hasOauth && !hasAzureAd && hasSecTest)
        record(suite, 'JWT deps in pom.xml', 'PASS');
      else
        record(suite, 'JWT deps in pom.xml', 'FAIL', `sec=${hasSecDep} oauth=${hasOauth} azureAd=${hasAzureAd}`);

      // SecurityConfig should have oauth2ResourceServer but use ROLE_ prefix (not APPROLE_)
      assertContains(dir, 'src/main/java/com/test/testsvc/config/SecurityConfig.java', 'ROLE_', suite, 'SecurityConfig uses ROLE_ prefix for JWT');
    } else {
      // authPattern = None — security headers still applied, but no OAuth2/JWT
      if (hasSecDep && !hasOauth && !hasAzureAd)
        record(suite, 'No OAuth2 deps in pom.xml (auth=None)', 'PASS');
      else
        record(suite, 'No OAuth2 deps in pom.xml (auth=None)', 'FAIL', `oauth=${hasOauth} azureAd=${hasAzureAd}`);
    }

    // Messaging checks
    if (combo.messaging === 'Azure Service Bus') {
      if (hasAsb && hasDepMgmt)
        record(suite, 'Service Bus deps in pom.xml', 'PASS');
      else
        record(suite, 'Service Bus deps in pom.xml', 'FAIL', `asb=${hasAsb} depMgmt=${hasDepMgmt}`);
    } else {
      if (!hasAsb)
        record(suite, 'No messaging deps in pom.xml', 'PASS');
      else
        record(suite, 'No messaging deps in pom.xml', 'FAIL');
    }

    assertNoAiTrace(dir, suite, combo.tag);
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// --- bff-springboot: 3 auth patterns ---
const bffSpringCombos = [
  { authPattern: 'OAuth2 + Azure AD', tag: 'oauth2' },
  { authPattern: 'JWT', tag: 'jwt' },
  { authPattern: 'None', tag: 'noauth' },
];

for (const combo of bffSpringCombos) {
  const suite = `bff-springboot/${combo.tag}`;
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'bff-springboot',
      variables: {
        projectName: `bff-sb-${combo.tag}`,
        className: 'BffTest',
        groupId: 'com.test',
        packageName: 'com.test.bfftest',
        packagePath: 'com/test/bfftest',
        artifactName: 'bfftest',
        authPattern: combo.authPattern,
        runtime: 'java',
      },
      layers: [],
    });

    record(suite, 'generates', 'PASS', `${files.length} files`);

    const pom = fileContent(dir, 'pom.xml');
    if (combo.authPattern === 'OAuth2 + Azure AD') {
      if (pom.includes('spring-boot-starter-security') && pom.includes('oauth2-resource-server'))
        record(suite, 'OAuth2 deps', 'PASS');
      else
        record(suite, 'OAuth2 deps', 'FAIL');
    } else if (combo.authPattern === 'JWT') {
      if (pom.includes('spring-boot-starter-security') && !pom.includes('oauth2-resource-server'))
        record(suite, 'JWT deps', 'PASS');
      else
        record(suite, 'JWT deps', 'FAIL');
    } else {
      if (!pom.includes('spring-boot-starter-security'))
        record(suite, 'No security deps', 'PASS');
      else
        record(suite, 'No security deps', 'FAIL');
    }

    // Resilience4j always present for BFF
    assertContains(dir, 'pom.xml', 'resilience4j', suite, 'Resilience4j present');
    assertContains(dir, 'pom.xml', 'spring-boot-starter-webflux', suite, 'WebFlux present');
    assertNoAiTrace(dir, suite, combo.tag);
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// --- bff-express: 3 auth patterns ---
const bffExpressCombos = [
  { authPattern: 'Azure AD Token Validation', tag: 'azuread', expectDeps: ['@azure/msal-node', 'jsonwebtoken', 'jwks-rsa'] },
  { authPattern: 'JWT', tag: 'jwt', expectDeps: ['jsonwebtoken'] },
  { authPattern: 'None', tag: 'noauth', expectDeps: [] },
];

for (const combo of bffExpressCombos) {
  const suite = `bff-express/${combo.tag}`;
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'bff-express',
      variables: {
        projectName: `bff-ex-${combo.tag}`,
        className: 'BffExTest',
        packageName: '',
        packagePath: '',
        artifactName: 'bffextest',
        authPattern: combo.authPattern,
        runtime: 'node',
      },
      layers: [],
    });

    record(suite, 'generates', 'PASS', `${files.length} files`);

    const pkg = fileContent(dir, 'package.json');
    let depsOk = true;
    for (const dep of combo.expectDeps) {
      if (!pkg.includes(dep)) {
        record(suite, `has ${dep}`, 'FAIL');
        depsOk = false;
      }
    }
    if (combo.tag === 'noauth') {
      if (pkg.includes('msal-node') || pkg.includes('jsonwebtoken')) {
        record(suite, 'no auth deps', 'FAIL', 'found auth deps when none expected');
        depsOk = false;
      }
    }
    if (depsOk) record(suite, 'auth deps correct', 'PASS');
    assertNoAiTrace(dir, suite, combo.tag);
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// --- bff-nextjs: 3 auth patterns ---
const bffNextjsCombos = [
  { authPattern: 'Azure AD Token Validation', tag: 'azuread', expectDeps: ['@azure/msal-node', 'jsonwebtoken', 'jwks-rsa'] },
  { authPattern: 'JWT', tag: 'jwt', expectDeps: ['jsonwebtoken'] },
  { authPattern: 'None', tag: 'noauth', expectDeps: [] },
];

for (const combo of bffNextjsCombos) {
  const suite = `bff-nextjs/${combo.tag}`;
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'bff-nextjs',
      variables: {
        projectName: `bff-nj-${combo.tag}`,
        className: 'BffNjTest',
        packageName: '',
        packagePath: '',
        artifactName: 'bffnjtest',
        authPattern: combo.authPattern,
        runtime: 'node',
      },
      layers: [],
    });

    record(suite, 'generates', 'PASS', `${files.length} files`);

    const pkg = fileContent(dir, 'package.json');
    let depsOk = true;
    for (const dep of combo.expectDeps) {
      if (!pkg.includes(dep)) {
        record(suite, `has ${dep}`, 'FAIL');
        depsOk = false;
      }
    }
    if (combo.tag === 'noauth' && (pkg.includes('msal-node') || pkg.includes('jsonwebtoken'))) {
      record(suite, 'no auth deps', 'FAIL');
      depsOk = false;
    }
    if (depsOk) record(suite, 'auth deps correct', 'PASS');
    assertNoAiTrace(dir, suite, combo.tag);
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// --- frontend-vite: 2 auth × 2 UI = 4 combos ---
const viteCombo = [
  { authPattern: 'Azure AD (MSAL)', uiLibrary: 'Tailwind CSS', tag: 'msal-tw' },
  { authPattern: 'Azure AD (MSAL)', uiLibrary: 'None', tag: 'msal-vanilla' },
  { authPattern: 'None', uiLibrary: 'Tailwind CSS', tag: 'noauth-tw' },
  { authPattern: 'None', uiLibrary: 'None', tag: 'noauth-vanilla' },
];

for (const combo of viteCombo) {
  const suite = `frontend-vite/${combo.tag}`;
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'frontend-vite',
      variables: {
        projectName: `fe-vite-${combo.tag}`,
        className: 'FeTest',
        packageName: '',
        packagePath: '',
        artifactName: 'fetest',
        authPattern: combo.authPattern,
        uiLibrary: combo.uiLibrary,
        runtime: 'node',
      },
      layers: [],
    });

    record(suite, 'generates', 'PASS', `${files.length} files`);

    const pkg = fileContent(dir, 'package.json');
    const viteConfig = fileContent(dir, 'vite.config.ts');
    const css = fileContent(dir, 'src/styles/globals.css');

    // Auth checks
    if (combo.authPattern === 'Azure AD (MSAL)') {
      if (pkg.includes('@azure/msal-browser') && pkg.includes('@azure/msal-react'))
        record(suite, 'MSAL deps', 'PASS');
      else
        record(suite, 'MSAL deps', 'FAIL');
    } else {
      if (!pkg.includes('msal'))
        record(suite, 'No MSAL deps', 'PASS');
      else
        record(suite, 'No MSAL deps', 'FAIL');
    }

    // UI checks
    if (combo.uiLibrary === 'Tailwind CSS') {
      if (pkg.includes('tailwindcss') && viteConfig.includes('tailwindcss') && css.includes('@import'))
        record(suite, 'Tailwind configured', 'PASS');
      else
        record(suite, 'Tailwind configured', 'FAIL');
    } else {
      if (!pkg.includes('tailwindcss') && !viteConfig.includes('tailwindcss') && css.includes('box-sizing'))
        record(suite, 'Vanilla CSS fallback', 'PASS');
      else
        record(suite, 'Vanilla CSS fallback', 'FAIL');
    }

    assertNoAiTrace(dir, suite, combo.tag);
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// --- frontend-nextjs: 2 auth × 2 UI = 4 combos ---
const nextjsFeCombos = [
  { authPattern: 'Azure AD (NextAuth + MSAL)', uiLibrary: 'Tailwind CSS', tag: 'nextauth-tw' },
  { authPattern: 'Azure AD (NextAuth + MSAL)', uiLibrary: 'None', tag: 'nextauth-vanilla' },
  { authPattern: 'None', uiLibrary: 'Tailwind CSS', tag: 'noauth-tw' },
  { authPattern: 'None', uiLibrary: 'None', tag: 'noauth-vanilla' },
];

for (const combo of nextjsFeCombos) {
  const suite = `frontend-nextjs/${combo.tag}`;
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'frontend-nextjs',
      variables: {
        projectName: `fe-next-${combo.tag}`,
        className: 'FeNjTest',
        packageName: '',
        packagePath: '',
        artifactName: 'fenjtest',
        authPattern: combo.authPattern,
        uiLibrary: combo.uiLibrary,
        runtime: 'node',
      },
      layers: [],
    });

    record(suite, 'generates', 'PASS', `${files.length} files`);

    const pkg = fileContent(dir, 'package.json');
    const layout = fileContent(dir, 'app/layout.tsx');
    const css = fileContent(dir, 'app/globals.css');

    // Auth checks
    if (combo.authPattern === 'Azure AD (NextAuth + MSAL)') {
      if (pkg.includes('next-auth') && pkg.includes('@azure/msal-node'))
        record(suite, 'NextAuth + MSAL deps', 'PASS');
      else
        record(suite, 'NextAuth + MSAL deps', 'FAIL');
    } else {
      if (!pkg.includes('next-auth') && !pkg.includes('msal'))
        record(suite, 'No auth deps', 'PASS');
      else
        record(suite, 'No auth deps', 'FAIL');
    }

    // UI checks
    if (combo.uiLibrary === 'Tailwind CSS') {
      if (pkg.includes('tailwindcss') && layout.includes('globals.css') && css.includes('@import'))
        record(suite, 'Tailwind configured', 'PASS');
      else
        record(suite, 'Tailwind configured', 'FAIL');
    } else {
      if (!pkg.includes('tailwindcss') && css.includes('box-sizing'))
        record(suite, 'Vanilla CSS fallback', 'PASS');
      else
        record(suite, 'Vanilla CSS fallback', 'FAIL');
    }

    assertNoAiTrace(dir, suite, combo.tag);
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// ──────────────────────────────────────────────
// SUITE 2: LAYER MERGE CORRECTNESS
// ───────────────────────────────────���──────────
console.log('\n╔══════════════════════════════════════════════╗');
console.log('║  SUITE 2: LAYER MERGE CORRECTNESS            ║');
console.log('╚══════════════════════════════════════════════╝');

// azure-sql layer merges pom.xml and application.yml
{
  const suite = 'layer/azure-sql';
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'backend-springboot',
      variables: {
        projectName: 'layer-sql-test',
        className: 'LayerSqlTest',
        groupId: 'com.test',
        packageName: 'com.test.layersqltest',
        packagePath: 'com/test/layersqltest',
        artifactName: 'layersqltest',
        authPattern: 'None',
        messaging: 'None',
        runtime: 'java',
        dbName: 'testdb',
      },
      layers: ['azure-sql'],
    });

    record(suite, 'generates with layer', 'PASS', `${files.length} files`);

    // pom.xml should have JPA + Flyway + SQL Server deps from merge
    const pom = fileContent(dir, 'pom.xml');
    const jpaOk = pom.includes('spring-boot-starter-data-jpa');
    const flywayOk = pom.includes('spring-boot-starter-flyway');
    const sqlOk = pom.includes('mssql-jdbc');
    if (jpaOk && flywayOk && sqlOk)
      record(suite, 'pom.xml merge (JPA+Flyway+MSSQL)', 'PASS');
    else
      record(suite, 'pom.xml merge', 'FAIL', `jpa=${jpaOk} flyway=${flywayOk} sql=${sqlOk}`);

    // application.yml should have Key Vault config (datasource no longer provided by azure-sql layer)
    const appYml = fileContent(dir, 'src/main/resources/application.yml');
    if (appYml.includes('keyvault'))
      record(suite, 'application.yml merge (keyvault config)', 'PASS');
    else
      record(suite, 'application.yml merge', 'FAIL', 'No keyvault config');

    // Migration file added
    assertFile(dir, 'src/main/resources/db/migration/V1__init.sql', suite, 'Migration file added');
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// ci-pipeline layer — Java runtime
{
  const suite = 'layer/ci-pipeline-java';
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'backend-springboot',
      variables: {
        projectName: 'layer-ci-java',
        className: 'LayerCiJava',
        groupId: 'com.test',
        packageName: 'com.test.layercijava',
        packagePath: 'com/test/layercijava',
        artifactName: 'layercijava',
        authPattern: 'None',
        messaging: 'None',
        runtime: 'java',
      },
      layers: ['ci-pipeline'],
    });

    record(suite, 'generates with layer', 'PASS');

    const ci = fileContent(dir, '.github/workflows/ci.yml');
    if (ci.includes('setup-java'))
      record(suite, 'CI uses setup-java', 'PASS');
    else
      record(suite, 'CI uses setup-java', 'FAIL');

    if (!ci.includes('setup-node'))
      record(suite, 'CI does not use setup-node', 'PASS');
    else
      record(suite, 'CI does not use setup-node', 'FAIL');
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// ci-pipeline layer — Node runtime
{
  const suite = 'layer/ci-pipeline-node';
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'frontend-vite',
      variables: {
        projectName: 'layer-ci-node',
        className: 'LayerCiNode',
        packageName: '',
        packagePath: '',
        artifactName: 'layercinode',
        authPattern: 'None',
        uiLibrary: 'None',
        runtime: 'node',
      },
      layers: ['ci-pipeline'],
    });

    record(suite, 'generates with layer', 'PASS');

    const ci = fileContent(dir, '.github/workflows/ci.yml');
    if (ci.includes('setup-node'))
      record(suite, 'CI uses setup-node', 'PASS');
    else
      record(suite, 'CI uses setup-node', 'FAIL');

    if (!ci.includes('setup-java'))
      record(suite, 'CI does not use setup-java', 'PASS');
    else
      record(suite, 'CI does not use setup-java', 'FAIL');
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// Multi-layer stacking: azure-sql + ci-pipeline
{
  const suite = 'layer/multi-stack';
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'backend-springboot',
      variables: {
        projectName: 'layer-multi',
        className: 'LayerMulti',
        groupId: 'com.test',
        packageName: 'com.test.layermulti',
        packagePath: 'com/test/layermulti',
        artifactName: 'layermulti',
        authPattern: 'OAuth2 + Azure AD',
        messaging: 'Azure Service Bus',
        runtime: 'java',
        dbName: 'multidb',
      },
      layers: ['azure-sql', 'ci-pipeline'],
    });

    record(suite, 'generates with 2 layers', 'PASS', `${files.length} files`);

    // All layer additions present
    assertFile(dir, 'src/main/resources/db/migration/V1__init.sql', suite, 'SQL migration present');
    assertFile(dir, '.github/workflows/ci.yml', suite, 'CI workflow present');

    // Merges applied
    assertContains(dir, 'pom.xml', 'spring-boot-starter-data-jpa', suite, 'JPA dep merged');
    assertContains(dir, 'pom.xml', 'spring-boot-starter-security', suite, 'Security dep present');
    assertContains(dir, 'pom.xml', 'spring-messaging-azure-servicebus', suite, 'Service Bus dep present');
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// ──────────────────────────────────────────────
// SUITE 3: BUILD VERIFICATION (all branches)
// Compile every generated project
// ──────────────────────────────────────────────
console.log('\n╔══════════════════════════════════════════════╗');
console.log('║  SUITE 3: BUILD VERIFICATION                 ║');
console.log('╚══════════════════════════════════════════════╝');

// Pick representative configs that cover all branches
const buildConfigs = [
  {
    name: 'backend-springboot/oauth2+asb+layers',
    config: {
      templateId: 'backend-springboot',
      variables: {
        projectName: 'build-be-full',
        className: 'BuildBeFull',
        groupId: 'com.test.build',
        packageName: 'com.test.build.buildbefull',
        packagePath: 'com/test/build/buildbefull',
        artifactName: 'buildbefull',
        authPattern: 'OAuth2 + Azure AD',
        messaging: 'Azure Service Bus',
        runtime: 'java',
        dbName: 'builddb',
      },
      layers: ['azure-sql', 'ci-pipeline'],
    },
    build: 'java',
  },
  {
    name: 'backend-springboot/noauth-bare',
    config: {
      templateId: 'backend-springboot',
      variables: {
        projectName: 'build-be-bare',
        className: 'BuildBeBare',
        groupId: 'com.test.build',
        packageName: 'com.test.build.buildbebare',
        packagePath: 'com/test/build/buildbebare',
        artifactName: 'buildbebare',
        authPattern: 'None',
        messaging: 'None',
        runtime: 'java',
      },
      layers: [],
    },
    build: 'java',
  },
  {
    name: 'bff-springboot/jwt',
    config: {
      templateId: 'bff-springboot',
      variables: {
        projectName: 'build-bff-sb',
        className: 'BuildBffSb',
        groupId: 'com.test.build',
        packageName: 'com.test.build.buildbffsb',
        packagePath: 'com/test/build/buildbffsb',
        artifactName: 'buildbffsb',
        authPattern: 'JWT',
        runtime: 'java',
      },
      layers: [],
    },
    build: 'java',
  },
  {
    name: 'bff-express/azuread',
    config: {
      templateId: 'bff-express',
      variables: {
        projectName: 'build-bff-ex',
        className: 'BuildBffEx',
        packageName: '',
        packagePath: '',
        artifactName: 'buildbffex',
        authPattern: 'Azure AD Token Validation',
        runtime: 'node',
      },
      layers: [],
    },
    build: 'node',
  },
  {
    name: 'bff-nextjs/jwt',
    config: {
      templateId: 'bff-nextjs',
      variables: {
        projectName: 'build-bff-nj',
        className: 'BuildBffNj',
        packageName: '',
        packagePath: '',
        artifactName: 'buildbffnj',
        authPattern: 'JWT',
        runtime: 'node',
      },
      layers: [],
    },
    build: 'node',
  },
  {
    name: 'frontend-vite/msal+tailwind',
    config: {
      templateId: 'frontend-vite',
      variables: {
        projectName: 'build-fe-vite',
        className: 'BuildFeVite',
        packageName: '',
        packagePath: '',
        artifactName: 'buildfevite',
        authPattern: 'Azure AD (MSAL)',
        uiLibrary: 'Tailwind CSS',
        runtime: 'node',
      },
      layers: [],
    },
    build: 'node',
  },
  {
    name: 'frontend-vite/vanilla',
    config: {
      templateId: 'frontend-vite',
      variables: {
        projectName: 'build-fe-vite-bare',
        className: 'BuildFeViteBare',
        packageName: '',
        packagePath: '',
        artifactName: 'buildfevitebare',
        authPattern: 'None',
        uiLibrary: 'None',
        runtime: 'node',
      },
      layers: [],
    },
    build: 'node',
  },
  {
    name: 'frontend-nextjs/nextauth+tailwind',
    config: {
      templateId: 'frontend-nextjs',
      variables: {
        projectName: 'build-fe-next',
        className: 'BuildFeNext',
        packageName: '',
        packagePath: '',
        artifactName: 'buildfenext',
        authPattern: 'Azure AD (NextAuth + MSAL)',
        uiLibrary: 'Tailwind CSS',
        runtime: 'node',
      },
      layers: [],
    },
    build: 'node',
  },
  {
    name: 'frontend-nextjs/vanilla',
    config: {
      templateId: 'frontend-nextjs',
      variables: {
        projectName: 'build-fe-next-bare',
        className: 'BuildFeNextBare',
        packageName: '',
        packagePath: '',
        artifactName: 'buildfenextbare',
        authPattern: 'None',
        uiLibrary: 'None',
        runtime: 'node',
      },
      layers: [],
    },
    build: 'node',
  },
];

for (const bc of buildConfigs) {
  const suite = `build/${bc.name}`;
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate(bc.config);
    record(suite, 'generates', 'PASS', `${files.length} files`);

    if (bc.build === 'java') {
      console.log('    mvn compile...');
      buildJava(dir);
      record(suite, 'mvn compile', 'PASS');

      // mvn test only works when Spring context can load without external deps
      // OAuth2 configs need a real issuer URI, so skip those
      const hasOAuth2 = bc.config.variables.authPattern === 'OAuth2 + Azure AD';
      if (hasOAuth2) {
        record(suite, 'mvn test', 'SKIP', 'OAuth2 needs Azure AD issuer at runtime');
      } else {
        console.log('    mvn test...');
        try {
          mvnTest(dir);
          record(suite, 'mvn test (contextLoads)', 'PASS');
        } catch (err) {
          record(suite, 'mvn test', 'FAIL', err.message.split('\n')[0]);
        }
      }
    } else {
      console.log('    npm install...');
      execSync('npm install', { cwd: dir, stdio: 'pipe', timeout: 120000 });
      record(suite, 'npm install', 'PASS');

      console.log('    tsc --noEmit...');
      execSync('npx tsc --noEmit', { cwd: dir, stdio: 'pipe', timeout: 60000 });
      record(suite, 'tsc --noEmit', 'PASS');
    }
  } catch (err) {
    record(suite, 'build', 'FAIL', err.message.split('\n')[0]);
  }
}

// ──────────────────────────────────────────────
// SUITE 4: RUNTIME VERIFICATION
// Start apps, hit health endpoints
// ──────────────────────────────────────────────
console.log('\n╔══════════════════════════════════════════════╗');
console.log('║  SUITE 4: RUNTIME VERIFICATION               ║');
console.log('╚══════════════════════════════════════════════╝');

// Only test Node apps (Java needs Spring Boot to start which needs
// a running DB for azure-sql configs — too heavy for local test)
const runtimeConfigs = [
  {
    name: 'bff-express',
    dir: join(OUT, 'build-bff-ex'),
    command: 'npx tsx src/index.ts',
    port: 3901,
    healthPath: '/api/health',
  },
];

for (const rc of runtimeConfigs) {
  const suite = `runtime/${rc.name}`;
  console.log(`\n--- ${suite} ---`);

  try {
    console.log(`    Starting on port ${rc.port}...`);
    const result = await startAndCheck(rc.dir, rc.command, rc.port, rc.healthPath, 20000);

    if (result.ok) {
      record(suite, `health endpoint (${rc.healthPath})`, 'PASS', `HTTP ${result.status}`);
      try {
        const body = JSON.parse(result.body);
        if (body.status === 'UP' || body.status === 'ok' || body.status === 'healthy')
          record(suite, 'health response body', 'PASS', `status=${body.status}`);
        else
          record(suite, 'health response body', 'FAIL', `unexpected status: ${body.status}`);
      } catch {
        record(suite, 'health response body', 'SKIP', 'non-JSON response');
      }
    } else {
      record(suite, 'health endpoint', 'FAIL', result.error);
    }
  } catch (err) {
    record(suite, 'runtime', 'FAIL', err.message);
  }
}

// ──────────────────────────────────────────────
// SUITE 5: EDGE CASES
// ──────────────────────────────────────────────
console.log('\n╔══════════════════════════════════════════════╗');
console.log('║  SUITE 5: EDGE CASES                         ║');
console.log('╚══════════════════════════════════════════════╝');

// Java version hardcoded to 21 in Dockerfile (javaVersion no longer a variable)
{
  const suite = 'edge/java21-dockerfile';
  console.log(`\n--- ${suite} ---`);

  const { dir } = generate({
    templateId: 'backend-springboot',
    variables: {
      projectName: 'edge-java21',
      className: 'EdgeJava21',
      groupId: 'com.test',
      packageName: 'com.test.edgejava21',
      packagePath: 'com/test/edgejava21',
      artifactName: 'edgejava21',
      authPattern: 'None',
      messaging: 'None',
      runtime: 'java',
    },
    layers: [],
  });

  const df = fileContent(dir, 'Dockerfile');
  if (df.includes('temurin:21'))
    record(suite, 'Dockerfile uses Java 21 (hardcoded)', 'PASS');
  else
    record(suite, 'Dockerfile uses Java 21 (hardcoded)', 'FAIL');
}

// All layers stacked on one template
{
  const suite = 'edge/all-layers';
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'backend-springboot',
      variables: {
        projectName: 'edge-all-layers',
        className: 'EdgeAllLayers',
        groupId: 'com.test',
        packageName: 'com.test.edgealllayers',
        packagePath: 'com/test/edgealllayers',
        artifactName: 'edgealllayers',
        authPattern: 'OAuth2 + Azure AD',
        messaging: 'Azure Service Bus',
        runtime: 'java',
        dbName: 'alldb',
        acrName: 'myacr',
        deployTarget: 'Azure Container Apps',
      },
      layers: ['azure-sql', 'ci-pipeline', 'azure-infra'],
    });

    record(suite, 'generates with all 3 layers', 'PASS', `${files.length} files`);
    assertFile(dir, 'src/main/resources/db/migration/V1__init.sql', suite, 'SQL migration');
    assertFile(dir, '.github/workflows/ci.yml', suite, 'CI workflow');
    assertFile(dir, 'infra/main.bicep', suite, 'Bicep infra');

    // CI should have Docker build section when acrName provided
    const ci = fileContent(dir, '.github/workflows/ci.yml');
    if (ci.includes('Docker image'))
      record(suite, 'CI has Docker build step', 'PASS');
    else
      record(suite, 'CI has Docker build step', 'FAIL');

    // Bicep should have Container Apps
    const bicep = fileContent(dir, 'infra/main.bicep');
    if (bicep.includes('containerApp') || bicep.includes('Container Apps'))
      record(suite, 'Bicep has Container Apps', 'PASS');
    else
      record(suite, 'Bicep has Container Apps', 'FAIL');
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// Empty className should not break anything
{
  const suite = 'edge/minimal-node-vars';
  console.log(`\n--- ${suite} ---`);

  try {
    const { files, dir } = generate({
      templateId: 'bff-express',
      variables: {
        projectName: 'minimal-app',
        className: 'MinimalApp',
        packageName: '',
        packagePath: '',
        artifactName: 'minimalapp',
        authPattern: 'None',
        runtime: 'node',
      },
      layers: [],
    });

    record(suite, 'generates with minimal vars', 'PASS', `${files.length} files`);
    assertFile(dir, 'package.json', suite, 'package.json exists');
    assertFile(dir, 'src/index.ts', suite, 'entry point exists');
  } catch (err) {
    record(suite, 'generation', 'FAIL', err.message);
  }
}

// ──────────────────────────────────────────────
// RESULTS
// ──────────────────────────────────────────────
console.log('\n╔══════════════════════════════════════════════╗');
console.log('║  FINAL RESULTS                               ║');
console.log('╚══════════════════════════════════════════════╝');
console.log(`  PASS: ${results.pass}`);
console.log(`  FAIL: ${results.fail}`);
console.log(`  SKIP: ${results.skip}`);
console.log(`  TOTAL: ${results.pass + results.fail + results.skip}`);

if (results.fail > 0) {
  console.log('\n  FAILURES:');
  for (const d of results.details.filter(d => d.status === 'FAIL')) {
    console.log(`    [${d.suite}] ${d.test}: ${d.detail}`);
  }
}

process.exit(results.fail > 0 ? 1 : 0);
